### ISSUE TITLE
Test helper for making sure a `performs` job was scheduled

### ISSUE THREAD

**Issue by matteeyah** [kaspth/active_job-performs#10]
## Summary

We are using `ActiveJob::Performs` to asynchronously do some recording processing. In some places we want to make sure that the job is scheduled.

The docs state what the job class naming convention is, so we were able to test it by "manually calculating" the job name and using that.

Here's 

```ruby
class Recording
  def process; end
  performs :process
end

class RecordingTest
  def creating_a_recording_triggers_processing
    new_recording = Recording.new

    assert_enqueued_jobs 1, only: Recording::ProcessJob do
      new_recording.save!
    end
  end
end
```

## Proposal

Create a test helper that calculates the `performs` job class name that makes testing the performs easier. e.g. `Recording.#{method_name}_job_class`.

Maybe something like this:

```ruby
class Recording
  def process; end
  performs :process
end

class RecordingTest
  def creating_a_recording_triggers_processing
    new_recording = Recording.new

    assert_enqueued_jobs 1, only: Recording.process_job_class do
      new_recording.save!
    end
  end
end
```

**Comment by matteeyah** [comment]
Actually, when I think about this some more, I might be solutionizing - the main thing is that I think there should be a way to check for the background execution. Testing that the job is scheduled is one way, there might be other ways that I'm not thinking of.

**Comment by kaspth** [comment]
Thanks for the issue!

I tried playing around with a few versions of this, the closest I got is something like:

```ruby
class RecordingTest
  def creating_a_recording_triggers_processing
    new_recording = Recording.new

    assert_enqueued_performs new_recording, :process do
      new_recording.save!
    end
  end
  
  def assert_enqueued_performs(receiver, name, count: 1, &)
    job = receiver.class.const_get("#{name.to_s.chomp("_later").camelize}Job")
    assert_enqueued_jobs(count, only: job, &)
  end
end
```

But I don't think it's that much of an improvement on `assert_enqueued_jobs 1, only: Recording::ProcessJob`, really.

I also think referring to the job class directly is clearer than us needing to maintain a  `Recording.process_job_class` method.

**Comment by kaspth** [comment]
Another option is to use `perform_enqueued_jobs` and test the behavior as well.

**Comment by kaspth** [comment]
> Actually, when I think about this some more, I might be solutionizing - the main thing is that I think there should be a way to check for the background execution.

Rails doesn't have anything like that built-in, the best bet is to test that something's enqueued.

**Comment by matteeyah** [comment]
The only reason why I dislike using the job class directly is because you might change the job class naming scheme at some point in the future. Once we upgrade, suddenly all tests fail, and it's not immediately apparent why.

**Comment by kaspth** [comment]
> The only reason why I dislike using the job class directly is because you might change the job class naming scheme at some point in the future.

I hear what you're saying here, which is why I wanted it to be stable when I picked the naming convention 2 years ago and so far it has. The only reason that it would change would be some unknown issue that could happen — and even if it did I'm pretty sure we could figure out a way to help apps upgrade easier.

However, if you still want `<>_job_class` methods, you could do something like this:

```ruby
# config/initializers/active_job/performs.rb
Rails.application.config.after_initialize do
  ActiveJob::Performs.prepend Module.new {
    def performs(method = nil, ...)
      super
      if method
        job = const_get "#{method}_job".classify
        define_singleton_method("#{method}_job_class") { job }
      end
    end
  }
end
```

**Comment by kaspth** [comment]
We've settled on not needing a specific test helper right now, I just forgot to close out the issue. Thanks!
