### ISSUE TITLE
Access job instance from inside method

### ISSUE THREAD

**Issue by doits** [kaspth/active_job-performs#11]
I'm just wondering if it can be made possible to access the `job` from inside the method, e.g. like this:

```rb
class Post < ActiveRecord::Base
  extend ActiveJob::Performs

  performs :publish

  def publish
     job # <-- The job currently running this method
  end
end
```

I've some methods for reporting the execution state for this job (e.g. `job.percent_done(21)`), but for this I need the job instance.

Maybe it could be passed optionally as a kword argument if defined?

```rb
class Post < ActiveRecord::Base
  extend ActiveJob::Performs

  performs :publish, pass_job: true

  def publish(job: nil)
     job
  end
end
```

... which would generate something like ...

```rb
  class PublishJob < Job
    def perform(post, *arguments, **options)
      options[:job] = self if pass_job?
      post.publish(*arguments, **options)
    end
  end
```

Or do you think this is out of scope for this gem?

**Comment by kaspth** [comment]
@doits hey, sorry for the long wait here! This is a pretty specific use-case so I think this is out of scope for the gem.

I still need to document this, but you can define `perform` manually via the block:

```ruby
performs :publish do
  def perform(post) = post.publish(job: self)
end
```

That might work if this is for a one-off case.

In general though, I'd probably make the metrics service available to the domain model object too, so it doesn't need to care about being run in a job or not.

Thanks again for the issue!
