### ISSUE TITLE
Exception passing hash to `performs` arguments

### ISSUE THREAD

**Issue by joelmoss** [kaspth/active_job-performs#8]
The following raises an ArgumentError...

```ruby
  performs :sync_messages!, queue_as: :default,
                            limits_concurrency: {
                              key: -> { "#{self.class}-#{arguments.first.to_global_id}" }
                            }
```

`solid_queue-0.1.2/lib/active_job/concurrency_controls.rb:18:in 'limits_concurrency': wrong number of arguments (given 1, expected 0; required keyword: key) (ArgumentError)`

I think because `limits_concurrency` is given a hash, which https://github.com/kaspth/active_job-performs/blob/main/lib/active_job/performs.rb#L73 cannot handle.

**Comment by joelmoss** [comment]
FYI: this fixes it, but not sure if it breaks anything else.

```ruby
    def apply_performs_to(job_class, **configs, &block)
      configs.each do |k, v|
        if v.is_a?(Hash)
          job_class.public_send(k, **v)
        else
          job_class.public_send(k, v)
        end
      end
      job_class.class_exec(&block) if block_given?
    end
```

**Comment by kaspth** [comment]
I was intending the block version to be for this type of more advanced configuration, so this should work:

```ruby
performs :sync_messages!, queue_as: :default do
  limits_concurrency key: -> { "#{self.class}-#{arguments.first.to_global_id}" }
end
```

I have been thinking of supporting `limits_concurrency` with this:

```ruby
# Users would have this in their app/jobs folder.
# Won't work yet since I need to support `ActiveJob::Performs::Job` as the default `performs` job class.
# app/jobs/active_job/performs/job.rb
class ActiveJob::Performs::Job < ApplicationJob
  if respond_to?(:limits_concurrency)
    # ActiveJob::Performs passes the model as the first argument, which is most often the appropriate key.
    # 
    # Then, use `module_parent_name` as the group, so `Post::PublishJob` and `Post::RetractJob`
    # uses `Post` and locks on a single `post`.
    # This way, users can't execute multiple jobs for the same model at the same time.
    # 
    # Override in individual calls with `performs :archive, concurrency_key: -> { _1.contact }, concurrency_group: nil`.
    limits_concurrency key: -> { _1 }, group: -> { module_parent_name }
  end
end
```

I'm still not settled on `module_parent_name` as the group, that might be a little aggressive. And using `self.class` like you've done may be the more appropriate default. What do you think?

I also need to override https://github.com/adrianthedev/solid_queue/blob/8bbc757d5d137335505b57202e759edc6a560944/lib/active_job/concurrency_controls.rb#L31 since it won't allow `ActiveRecord::AssociatedObject`s to be decomposed (your use of `to_global_id` gets around that too, so I suppose that could be our default too).

**Comment by joelmoss** [comment]
Ah ok. Well the block form works, so I'll use that. Not sure anything extra is needed here, even for `limits_concurrency`, so long as it can be configured via `performs`.

**Comment by kaspth** [comment]
Sounds good! I'll close this out.

I still think there's something to assigning defaults for `limits_concurrency`, so people don't have to configure the same across every `performs` call.

Although you can also share the config per class like this:

```ruby
class Post < ApplicationRecord
  performs do
    limits_concurrency key: -> { _1.id }
  end

  performs :sync_messages! # Reuses configuration from the general `performs` call above.
end
```

**Comment by kaspth** [comment]
Just posting these notes for my future self:

```ruby
class ActiveJob::Performs::Job < ApplicationJob
  if respond_to?(:limits_concurrency)
    # ActiveJob::Performs passes the model as the first argument, which is most likely what we want as the key.
    # 
    # Override in individual calls with `performs :archive, concurrency_key: -> { _1.contact }
    # 
    # Because we're always nesting within the namespace of a model our class name + id will be enough to lock jobs
    # Otherwise we'd have Post::Publisher::PublishJob with a `concurrency_key` of `Post::Publisher::PublishJob/Post::Publisher/1`
    # So we can omit the model class name and use the `id` for the key part.
    limits_concurrency key: -> { _1.id }
  end
end
```
